version: '3.8'
services:
  app:
    container_name: sabor_lena_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8050:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres
    networks:
      - sabor_net

  postgres:
    image: postgres:15-alpine
    container_name: sabor_lena_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: sabor_lena
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - sabor_net

networks:
  sabor_net:
    driver: bridge

volumes:
  postgres_data_prod:
